name: Packer Format and Validate

on:
  pull_request:
    branches:
      - main
      - feature-A05


jobs:
  ami_format_check:
    name: ami_format_check
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Mysql@55
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: mysql
          MYSQL_PASSWORD: Mysql@55
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -r webapp.zip .
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build with Maven
        run: mvn clean install -DskipTests
        env:
          DATABASE_HOSTNAME: jdbc:mysql://localhost:3306/mysqldb?createDatabaseIfNotExist=true
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: Mysql@55
          S3_BUCKET_NAME: sample_value
      - name: Run tests
        run: mvn test
        env:
          DATABASE_HOSTNAME: jdbc:mysql://localhost:3306/mysqldb?createDatabaseIfNotExist=true
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: Mysql@55
          S3_BUCKET_NAME: sample_value
      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip -o packer_1.7.4_linux_amd64.zip -d packer_temp
          sudo mv -f packer_temp/packer /usr/local/bin         
        shell: bash

      - name: Packer Format
        run: |
          cd packer
          packer fmt -check .
        shell: bash

      - name: Packer Validate
        run: |
          cd packer
          pwd
          packer init ./
          if ! packer validate aws.pkr.hcl; then
            echo "Packer validation check failed."
            exit 1
          else
            echo "Packer validation check passed"
          fi
        shell: bash
        
