name: CI

on:
  pull_request:
    branches:
      - main
      - feature-A05

jobs:
  integration_test:
    name: Integration test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Mysql@55
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: mysql
          MYSQL_PASSWORD: Mysql@55
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

  build-image:
    name: Build Custom Amazon Machine Image (AMI) Using Packer
    runs-on: ubuntu-latest
    needs: integration_test

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Mysql@55
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: mysql
          MYSQL_PASSWORD: Mysql@55
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip repository code
        run: |
          zip -r webapp.zip .
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Build with Maven
        run: mvn clean install -DskipTests
        env:
          DATABASE_HOSTNAME: jdbc:mysql://localhost:3306/mysqldb?createDatabaseIfNotExist=true
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: Mysql@55
          S3_BUCKET_NAME: sample_value
          SNS_TOPIC_ARN: sns_topic
      - name: Run tests
        run: mvn test
        env:
          DATABASE_HOSTNAME: jdbc:mysql://localhost:3306/mysqldb?createDatabaseIfNotExist=true
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: Mysql@55
          S3_BUCKET_NAME: sample_value
          SNS_TOPIC_ARN: sns_topic
      - name: Packer setup
        uses: hashicorp/setup-packer@main
        with:
          packer-version: 1.7.4

      - name: Run packer
        id: packer
        run: |
          cd packer
          packer init aws.pkr.hcl
          packer build -machine-readable aws.pkr.hcl | tee packer.log
          AMI_ID=$(awk -F, '/artifact,0,id/ {print $6}' packer.log | cut -d: -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      - name: Sharing the AMI with Demo Account
        run: |
          aws ec2 modify-image-attribute --image-id ${{ steps.packer.outputs.ami_id }} --launch-permission '{"Add":[{"UserId": "${{ secrets.DEMO_ACCOUNT_ID}}" }]}'
      
        
      - name: AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.4
        with:
          version: 2
      - run: |
          aws ec2 create-launch-template-version --launch-template-name csye6225_launch_template --source-version 1 --launch-template-data "{\"ImageId\":\"${{ steps.packer.outputs.ami_id }}\"}"
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name WebAppAutoScaleGroup --launch-template LaunchTemplateName=csye6225_launch_template,Version='$Latest'
          aws autoscaling start-instance-refresh --auto-scaling-group-name WebAppAutoScaleGroup